### ISSUE TITLE
Missing face_tracker 

### ISSUE THREAD

**Issue by jrussino** [pgigioli/darknet_ros#1]
I tried installing this for ROS Jade on Ubuntu 15.04
When I try to build the node (via catkin_make), I get the following error:

-- +++ processing catkin package: 'darknet_ros'
-- ==> add_subdirectory(darknet_ros)
CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "face_tracker" with
  any of the following names:

    face_trackerConfig.cmake
    face_tracker-config.cmake

  Add the installation prefix of "face_tracker" to CMAKE_PREFIX_PATH or set
  "face_tracker_DIR" to a directory containing one of the above files.  If
  "face_tracker" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  darknet_ros/CMakeLists.txt:6 (find_package)

Where can I find this dependency? As far as I can tell, there is no ros-jade-face-tracker package, and I couldn't find a repo with that name via google/github search.

**Comment by pgigioli** [comment]
Oh sorry, that's because face_tracker is a package that I made.  You can check out the repo here https://github.com/pgigioli/face_tracker.  I trained a face detector using YOLO and the face_tracker  keeps track of the bounding box coordinates from the detector so that the robot can align its camera with the detected face.

If you don't want to use the face_tracker package, in the darknet_ros CMakeLists.txt, simply delete face_tracker from the find_package statement, and remove the yolo_face_detector and yolo_person_detector executables.  

I forgot that I linked my repo to the google groups page so perhaps I'll make a separate version of this package for my own purposes.  Thanks for bringing this up.
